<?php
/**
 * SearchItemSeller
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AliseeksApi\Model;

use \ArrayAccess;
use \AliseeksApi\ObjectSerializer;

/**
 * SearchItemSeller Class Doc Comment
 *
 * @category Class
 * @description The seller of the search item
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchItemSeller implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SearchItemSeller';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'store_name' => 'string',
        'name' => 'string',
        'positive_feedback' => 'int',
        'negative_feedback' => 'int',
        'seller_score' => 'int',
        'total_feedback' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'store_name' => null,
        'name' => null,
        'positive_feedback' => 'int32',
        'negative_feedback' => 'int32',
        'seller_score' => 'int32',
        'total_feedback' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'store_name' => 'storeName',
        'name' => 'name',
        'positive_feedback' => 'positiveFeedback',
        'negative_feedback' => 'negativeFeedback',
        'seller_score' => 'sellerScore',
        'total_feedback' => 'totalFeedback'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'store_name' => 'setStoreName',
        'name' => 'setName',
        'positive_feedback' => 'setPositiveFeedback',
        'negative_feedback' => 'setNegativeFeedback',
        'seller_score' => 'setSellerScore',
        'total_feedback' => 'setTotalFeedback'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'store_name' => 'getStoreName',
        'name' => 'getName',
        'positive_feedback' => 'getPositiveFeedback',
        'negative_feedback' => 'getNegativeFeedback',
        'seller_score' => 'getSellerScore',
        'total_feedback' => 'getTotalFeedback'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['store_name'] = isset($data['store_name']) ? $data['store_name'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['positive_feedback'] = isset($data['positive_feedback']) ? $data['positive_feedback'] : null;
        $this->container['negative_feedback'] = isset($data['negative_feedback']) ? $data['negative_feedback'] : null;
        $this->container['seller_score'] = isset($data['seller_score']) ? $data['seller_score'] : null;
        $this->container['total_feedback'] = isset($data['total_feedback']) ? $data['total_feedback'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets store_name
     *
     * @return string|null
     */
    public function getStoreName()
    {
        return $this->container['store_name'];
    }

    /**
     * Sets store_name
     *
     * @param string|null $store_name The name of the seller store
     *
     * @return $this
     */
    public function setStoreName($store_name)
    {
        $this->container['store_name'] = $store_name;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the seller
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets positive_feedback
     *
     * @return int|null
     */
    public function getPositiveFeedback()
    {
        return $this->container['positive_feedback'];
    }

    /**
     * Sets positive_feedback
     *
     * @param int|null $positive_feedback The amount of positive feedback for the seller
     *
     * @return $this
     */
    public function setPositiveFeedback($positive_feedback)
    {
        $this->container['positive_feedback'] = $positive_feedback;

        return $this;
    }

    /**
     * Gets negative_feedback
     *
     * @return int|null
     */
    public function getNegativeFeedback()
    {
        return $this->container['negative_feedback'];
    }

    /**
     * Sets negative_feedback
     *
     * @param int|null $negative_feedback The amount of negative feedback for the seller
     *
     * @return $this
     */
    public function setNegativeFeedback($negative_feedback)
    {
        $this->container['negative_feedback'] = $negative_feedback;

        return $this;
    }

    /**
     * Gets seller_score
     *
     * @return int|null
     */
    public function getSellerScore()
    {
        return $this->container['seller_score'];
    }

    /**
     * Sets seller_score
     *
     * @param int|null $seller_score The score of the seller
     *
     * @return $this
     */
    public function setSellerScore($seller_score)
    {
        $this->container['seller_score'] = $seller_score;

        return $this;
    }

    /**
     * Gets total_feedback
     *
     * @return int|null
     */
    public function getTotalFeedback()
    {
        return $this->container['total_feedback'];
    }

    /**
     * Sets total_feedback
     *
     * @param int|null $total_feedback The total amount of feedback for the seller
     *
     * @return $this
     */
    public function setTotalFeedback($total_feedback)
    {
        $this->container['total_feedback'] = $total_feedback;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


