<?php
/**
 * SkuPriceOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AliseeksApi\Model;

use \ArrayAccess;
use \AliseeksApi\ObjectSerializer;

/**
 * SkuPriceOption Class Doc Comment
 *
 * @category Class
 * @description A SKU with price information
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SkuPriceOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SkuPriceOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'original_price' => '\AliseeksApi\Model\Amount',
        'discounted_price' => '\AliseeksApi\Model\Amount',
        'bulk_price' => '\AliseeksApi\Model\Amount',
        'bulk_quantity' => 'int',
        'sku_image' => 'string',
        'discounted_stock' => 'int',
        'stock' => 'int',
        'sku_identifier' => 'string',
        'properties' => '\AliseeksApi\Model\SkuPriceOptionProperty[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'original_price' => null,
        'discounted_price' => null,
        'bulk_price' => null,
        'bulk_quantity' => 'int32',
        'sku_image' => null,
        'discounted_stock' => 'int32',
        'stock' => 'int32',
        'sku_identifier' => null,
        'properties' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'original_price' => 'originalPrice',
        'discounted_price' => 'discountedPrice',
        'bulk_price' => 'bulkPrice',
        'bulk_quantity' => 'bulkQuantity',
        'sku_image' => 'skuImage',
        'discounted_stock' => 'discountedStock',
        'stock' => 'stock',
        'sku_identifier' => 'skuIdentifier',
        'properties' => 'properties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'original_price' => 'setOriginalPrice',
        'discounted_price' => 'setDiscountedPrice',
        'bulk_price' => 'setBulkPrice',
        'bulk_quantity' => 'setBulkQuantity',
        'sku_image' => 'setSkuImage',
        'discounted_stock' => 'setDiscountedStock',
        'stock' => 'setStock',
        'sku_identifier' => 'setSkuIdentifier',
        'properties' => 'setProperties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'original_price' => 'getOriginalPrice',
        'discounted_price' => 'getDiscountedPrice',
        'bulk_price' => 'getBulkPrice',
        'bulk_quantity' => 'getBulkQuantity',
        'sku_image' => 'getSkuImage',
        'discounted_stock' => 'getDiscountedStock',
        'stock' => 'getStock',
        'sku_identifier' => 'getSkuIdentifier',
        'properties' => 'getProperties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['original_price'] = isset($data['original_price']) ? $data['original_price'] : null;
        $this->container['discounted_price'] = isset($data['discounted_price']) ? $data['discounted_price'] : null;
        $this->container['bulk_price'] = isset($data['bulk_price']) ? $data['bulk_price'] : null;
        $this->container['bulk_quantity'] = isset($data['bulk_quantity']) ? $data['bulk_quantity'] : null;
        $this->container['sku_image'] = isset($data['sku_image']) ? $data['sku_image'] : null;
        $this->container['discounted_stock'] = isset($data['discounted_stock']) ? $data['discounted_stock'] : null;
        $this->container['stock'] = isset($data['stock']) ? $data['stock'] : null;
        $this->container['sku_identifier'] = isset($data['sku_identifier']) ? $data['sku_identifier'] : null;
        $this->container['properties'] = isset($data['properties']) ? $data['properties'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets original_price
     *
     * @return \AliseeksApi\Model\Amount|null
     */
    public function getOriginalPrice()
    {
        return $this->container['original_price'];
    }

    /**
     * Sets original_price
     *
     * @param \AliseeksApi\Model\Amount|null $original_price original_price
     *
     * @return $this
     */
    public function setOriginalPrice($original_price)
    {
        $this->container['original_price'] = $original_price;

        return $this;
    }

    /**
     * Gets discounted_price
     *
     * @return \AliseeksApi\Model\Amount|null
     */
    public function getDiscountedPrice()
    {
        return $this->container['discounted_price'];
    }

    /**
     * Sets discounted_price
     *
     * @param \AliseeksApi\Model\Amount|null $discounted_price discounted_price
     *
     * @return $this
     */
    public function setDiscountedPrice($discounted_price)
    {
        $this->container['discounted_price'] = $discounted_price;

        return $this;
    }

    /**
     * Gets bulk_price
     *
     * @return \AliseeksApi\Model\Amount|null
     */
    public function getBulkPrice()
    {
        return $this->container['bulk_price'];
    }

    /**
     * Sets bulk_price
     *
     * @param \AliseeksApi\Model\Amount|null $bulk_price bulk_price
     *
     * @return $this
     */
    public function setBulkPrice($bulk_price)
    {
        $this->container['bulk_price'] = $bulk_price;

        return $this;
    }

    /**
     * Gets bulk_quantity
     *
     * @return int|null
     */
    public function getBulkQuantity()
    {
        return $this->container['bulk_quantity'];
    }

    /**
     * Sets bulk_quantity
     *
     * @param int|null $bulk_quantity The quantity that needs to be ordered to qualify for the bulk discount
     *
     * @return $this
     */
    public function setBulkQuantity($bulk_quantity)
    {
        $this->container['bulk_quantity'] = $bulk_quantity;

        return $this;
    }

    /**
     * Gets sku_image
     *
     * @return string|null
     */
    public function getSkuImage()
    {
        return $this->container['sku_image'];
    }

    /**
     * Sets sku_image
     *
     * @param string|null $sku_image The image associated with the sku
     *
     * @return $this
     */
    public function setSkuImage($sku_image)
    {
        $this->container['sku_image'] = $sku_image;

        return $this;
    }

    /**
     * Gets discounted_stock
     *
     * @return int|null
     */
    public function getDiscountedStock()
    {
        return $this->container['discounted_stock'];
    }

    /**
     * Sets discounted_stock
     *
     * @param int|null $discounted_stock The stock left at the discounted price
     *
     * @return $this
     */
    public function setDiscountedStock($discounted_stock)
    {
        $this->container['discounted_stock'] = $discounted_stock;

        return $this;
    }

    /**
     * Gets stock
     *
     * @return int|null
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     *
     * @param int|null $stock The stock left for the sku
     *
     * @return $this
     */
    public function setStock($stock)
    {
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets sku_identifier
     *
     * @return string|null
     */
    public function getSkuIdentifier()
    {
        return $this->container['sku_identifier'];
    }

    /**
     * Sets sku_identifier
     *
     * @param string|null $sku_identifier The identifier of the sku
     *
     * @return $this
     */
    public function setSkuIdentifier($sku_identifier)
    {
        $this->container['sku_identifier'] = $sku_identifier;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return \AliseeksApi\Model\SkuPriceOptionProperty[]|null
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param \AliseeksApi\Model\SkuPriceOptionProperty[]|null $properties The properties associated with this sku
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->container['properties'] = $properties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


