<?php
/**
 * PriceSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * PriceSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description A summary of prices for a product
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PriceSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceSummary"
     */
    public function testPriceSummary()
    {
    }

    /**
     * Test attribute "original_amount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "unit_original_amount"
     */
    public function testPropertyUnitOriginalAmount()
    {
    }

    /**
     * Test attribute "discounted_amount"
     */
    public function testPropertyDiscountedAmount()
    {
    }

    /**
     * Test attribute "unit_discounted_amount"
     */
    public function testPropertyUnitDiscountedAmount()
    {
    }

    /**
     * Test attribute "bulk_amount"
     */
    public function testPropertyBulkAmount()
    {
    }

    /**
     * Test attribute "unit_bulk_amount"
     */
    public function testPropertyUnitBulkAmount()
    {
    }
}
