<?php
/**
 * ProductReviewsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * ProductReviewsTest Class Doc Comment
 *
 * @category    Class
 * @description Reviews on a product
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductReviewsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductReviews"
     */
    public function testProductReviews()
    {
    }

    /**
     * Test attribute "five_star_count"
     */
    public function testPropertyFiveStarCount()
    {
    }

    /**
     * Test attribute "four_star_count"
     */
    public function testPropertyFourStarCount()
    {
    }

    /**
     * Test attribute "three_star_count"
     */
    public function testPropertyThreeStarCount()
    {
    }

    /**
     * Test attribute "two_star_count"
     */
    public function testPropertyTwoStarCount()
    {
    }

    /**
     * Test attribute "one_star_count"
     */
    public function testPropertyOneStarCount()
    {
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "positive_count"
     */
    public function testPropertyPositiveCount()
    {
    }

    /**
     * Test attribute "negative_count"
     */
    public function testPropertyNegativeCount()
    {
    }

    /**
     * Test attribute "neutral_count"
     */
    public function testPropertyNeutralCount()
    {
    }

    /**
     * Test attribute "ratings"
     */
    public function testPropertyRatings()
    {
    }
}
