<?php
/**
 * ProductSellerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * ProductSellerTest Class Doc Comment
 *
 * @category    Class
 * @description Seller of an AliExpress product
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductSellerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductSeller"
     */
    public function testProductSeller()
    {
    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "store_url"
     */
    public function testPropertyStoreUrl()
    {
    }

    /**
     * Test attribute "store_name"
     */
    public function testPropertyStoreName()
    {
    }

    /**
     * Test attribute "seller_level"
     */
    public function testPropertySellerLevel()
    {
    }

    /**
     * Test attribute "positive_feedback_rate"
     */
    public function testPropertyPositiveFeedbackRate()
    {
    }
}
