<?php
/**
 * ProductPriceOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * ProductPriceOptionTest Class Doc Comment
 *
 * @category    Class
 * @description A product price option
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductPriceOptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductPriceOption"
     */
    public function testProductPriceOption()
    {
    }

    /**
     * Test attribute "max_amount"
     */
    public function testPropertyMaxAmount()
    {
    }

    /**
     * Test attribute "max_amount_per_piece"
     */
    public function testPropertyMaxAmountPerPiece()
    {
    }

    /**
     * Test attribute "min_amount"
     */
    public function testPropertyMinAmount()
    {
    }

    /**
     * Test attribute "min_amount_per_piece"
     */
    public function testPropertyMinAmountPerPiece()
    {
    }

    /**
     * Test attribute "minimum_purchase"
     */
    public function testPropertyMinimumPurchase()
    {
    }

    /**
     * Test attribute "processing_time"
     */
    public function testPropertyProcessingTime()
    {
    }

    /**
     * Test attribute "bulk_option"
     */
    public function testPropertyBulkOption()
    {
    }
}
