<?php
/**
 * ProductSkuTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * ProductSkuTest Class Doc Comment
 *
 * @category    Class
 * @description The pricing option of the product
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductSkuTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductSku"
     */
    public function testProductSku()
    {
    }

    /**
     * Test attribute "property_identifiers"
     */
    public function testPropertyPropertyIdentifiers()
    {
    }

    /**
     * Test attribute "property_value_ids"
     */
    public function testPropertyPropertyValueIds()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "discounted_price"
     */
    public function testPropertyDiscountedPrice()
    {
    }

    /**
     * Test attribute "bulk_price"
     */
    public function testPropertyBulkPrice()
    {
    }

    /**
     * Test attribute "bulk_quantity"
     */
    public function testPropertyBulkQuantity()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "image_url"
     */
    public function testPropertyImageUrl()
    {
    }
}
