<?php
/**
 * SearchRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * SearchRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Non realtime search request body
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SearchRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchRequest"
     */
    public function testSearchRequest()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "sort"
     */
    public function testPropertySort()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "include_subcategories"
     */
    public function testPropertyIncludeSubcategories()
    {
    }

    /**
     * Test attribute "sort_direction"
     */
    public function testPropertySortDirection()
    {
    }

    /**
     * Test attribute "ratings_range"
     */
    public function testPropertyRatingsRange()
    {
    }

    /**
     * Test attribute "quantity_range"
     */
    public function testPropertyQuantityRange()
    {
    }

    /**
     * Test attribute "price_range"
     */
    public function testPropertyPriceRange()
    {
    }

    /**
     * Test attribute "unit_price_range"
     */
    public function testPropertyUnitPriceRange()
    {
    }

    /**
     * Test attribute "order_range"
     */
    public function testPropertyOrderRange()
    {
    }

    /**
     * Test attribute "item_id_range"
     */
    public function testPropertyItemIdRange()
    {
    }

    /**
     * Test attribute "freight_types"
     */
    public function testPropertyFreightTypes()
    {
    }

    /**
     * Test attribute "skip"
     */
    public function testPropertySkip()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "scroll_pagination"
     */
    public function testPropertyScrollPagination()
    {
    }

    /**
     * Test attribute "scroll_identifier"
     */
    public function testPropertyScrollIdentifier()
    {
    }
}
