<?php
/**
 * SearchItemSellerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * SearchItemSellerTest Class Doc Comment
 *
 * @category    Class
 * @description The seller of the search item
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SearchItemSellerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchItemSeller"
     */
    public function testSearchItemSeller()
    {
    }

    /**
     * Test attribute "store_name"
     */
    public function testPropertyStoreName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "positive_feedback"
     */
    public function testPropertyPositiveFeedback()
    {
    }

    /**
     * Test attribute "negative_feedback"
     */
    public function testPropertyNegativeFeedback()
    {
    }

    /**
     * Test attribute "seller_score"
     */
    public function testPropertySellerScore()
    {
    }

    /**
     * Test attribute "total_feedback"
     */
    public function testPropertyTotalFeedback()
    {
    }
}
