<?php
/**
 * SkuPriceOptionPropertyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AliseeksApi;

/**
 * SkuPriceOptionPropertyTest Class Doc Comment
 *
 * @category    Class
 * @description A property of a sku of a product
 * @package     AliseeksApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SkuPriceOptionPropertyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SkuPriceOptionProperty"
     */
    public function testSkuPriceOptionProperty()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "property_name"
     */
    public function testPropertyPropertyName()
    {
    }

    /**
     * Test attribute "value_id"
     */
    public function testPropertyValueId()
    {
    }

    /**
     * Test attribute "value_name"
     */
    public function testPropertyValueName()
    {
    }

    /**
     * Test attribute "value_display_name"
     */
    public function testPropertyValueDisplayName()
    {
    }

    /**
     * Test attribute "ship_from_country"
     */
    public function testPropertyShipFromCountry()
    {
    }
}
