<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aliseeks API
 *
 * AliExpress product searching and product details retrieval API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AliseeksApi;

use \AliseeksApi\Configuration;
use \AliseeksApi\ApiException;
use \AliseeksApi\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  AliseeksApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getProduct
     *
     * Get products details as an aggregated request from AliExpress in realtime..
     *
     */
    public function testGetProduct()
    {
    }

    /**
     * Test case for getProductDetails
     *
     * Gets product details from AliExpress in realtime..
     *
     */
    public function testGetProductDetails()
    {
    }

    /**
     * Test case for getProductHtmlDescription
     *
     * Get product HTML description from AliExpress in realtime..
     *
     */
    public function testGetProductHtmlDescription()
    {
    }

    /**
     * Test case for getProductShipping
     *
     * Gets product shipping information AliExpress in realtime..
     *
     */
    public function testGetProductShipping()
    {
    }

    /**
     * Test case for getProductSkus
     *
     * Gets product skus / variation information from AliExpress in realtime..
     *
     */
    public function testGetProductSkus()
    {
    }
}
